### ISSUE TITLE
Image won't load if there are more than one images in data.csv

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/design_explorer_lite#20]
I think it is because currently it is looking for a full match of "img" as key instead of searching start from "img", as "img_1", "img_planview", etc are also be header.

In terms of muti-image, I would suggest to show them all by default.

**Comment by chriswmackey** [comment]
A, I didn't realize multi-image simulations were possible.  What do you think the default should be in this case @MingboPeng ?  Should we load up just img_1 or should we try to load all images?

Also is the convention in the Design Explorer CSV just that any image column starts with img?  In this case, I can fix the bug at least.

**Comment by MingboPeng** [comment]
@chriswmackey  in current Design Explorer, it is using the first of item starts with "img", and all other images will be shown as an option in dropdown  (an example: https://goo.gl/pTRwF1)
![image](https://user-images.githubusercontent.com/9031066/43348048-1b82db6c-91c6-11e8-9547-47f26d9d695b.png)

**Comment by chriswmackey** [comment]
Ah, nice! I don't know why I never stumbled upon this feature.  Ok, I will add in a patch for these cases now.

For the long term, what do you think is the best way of setting up Design Explorer Lite for this?
Should the default be to show only the first img column and then people can add the other images to be next to each other with the settings_lite.json?

Or should we try to have a similar dropdown menu as the full Design Explorer?

**Comment by chriswmackey** [comment]
@MingboPeng ,
I have fixed this issue and it should work now:
https://github.com/ladybug-tools/design_explorer_lite/commit/ee4930cf23e7d4bff5957febcfa4db3d003a2921

In the course of setting everything up, it seemed better to have the default show all images and then, if you want to create an interface that has fewer images, you make a settings_lite.json file that does not have these images listed under the `'visuals'` property.

Also, in order to implement this, I had to make a minor change to the settings_lite.json file, which is that, in order to customize the images, the name of the image visual under `'visuals'` now has to match the name of the img column in the csv.  This seemed like the cleanest way to implement it, allowing you to customize the width and height of each image in the study.

If you feel we should change any of this, please feel free to re-open the issue.
